//@ui5-bundle 02_remotesource_approuter/Component-preload.js
jQuery.sap.registerPreloadedModules({
"version":"2.0",
"modules":{
	"02_remotesource_approuter/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent"],function(n){"use strict";return n.extend("sap.ui.demo.Component",{metadata:{interfaces:["sap.ui.core.IAsyncContentCreation"],manifest:"json"},init:function(){n.prototype.init.apply(this,arguments)}})});
},
	"02_remotesource_approuter/controller/App.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller","sap/ui/model/json/JSONModel"],function(e,t){"use strict";return e.extend("sap.ui.demo.controller.App",{incrementBy1:function(){let e=this.getView().byId("counter");let t=parseInt(e.getText());let n=t+1;e.setText(n)},onInit:function(){let e=new t(sap.ui.require.toUrl("sap/ui/demo/Data.json"));this.getView().setModel(e)}})});
},
	"02_remotesource_approuter/manifest.json":'{"sap.app":{"id":"02_remotesource_approuter","applicationVersion":{"version":"1.0.0"},"dataSources":{"youTubeAPI":{"uri":"/youTubeURL/youtube/v3/playlistItems?part=contentDetails%2Csnippet&playlistId=PL6RpkC85SLQBM78mD6AiJ1vKlSB7OWtUz&key=API_KEY","type":"JSON"}}},"sap.ui5":{"rootView":{"viewName":"sap.ui.demo.view.App","type":"XML","id":"app"},"models":{"youTubeModel":{"dataSource":"youTubeAPI"}}}}',
	"02_remotesource_approuter/view/App.view.xml":'<mvc:View\n   xmlns="sap.m"\n   xmlns:mvc="sap.ui.core.mvc"\n   controllerName="sap.ui.demo.controller.App"\n   xmlns:html="http://www.w3.org/1999/xhtml"><html:style>\n        .redBold {\n            color: red;\n            font-weight: bold;\n        }\n   </html:style><Button \n      text="increment by 1"\n      press=".incrementBy1" /><Text id="counter" text="0"/><List\n      id="episodeOverview"\n      headerText="{youTubeModel>/items/1/snippet/channelTitle}"\n      items="{youTubeModel>/items}"><items><StandardListItem\n            title="{youTubeModel>snippet/title}"\n            description="{youTubeModel>snippet/publishedAt}" /></items></List><Text class="redBold" text="In case you don\'t see any data: You need a valid" /><Link\n      class="redBold"\n      text="Google Developer API Key"\n      target="_blank"\n      href="https://console.developers.google.com/apis/credentials" /><Text class="redBold" text="and attach it to the value for \'youTubeAPI\' in the manifest.json to make the API call work." /></mvc:View>'
}});
